[package]
name = "http-response"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
sea-orm = { workspace = true }
futures-util = { workspace = true }